name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker image build -t nolanmckenna/rest-app:latest .
      
    - name: Run the Docker Container 
      run: docker run --name rest-test -d -p 5001:2000 nolanmckenna/rest-app 
      
    - name: Wait for container to start
      run: sleep 10

    - name: Test /fib sequence
      run: curl http://localhost:5001/fib

    - name: Stop Container
      run: docker stop rest-test

    - name: Remove container
      run: docker rm rest-test
      
